/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './js/**/*.js',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': '#272e2a',
        'surface-container-highest': '#212724',
        'outline-variant': '#434946',
        'surface': '#0d0f0e',
        'primary-container': '#2c4e3b',
        'surface-container': '#171a19',
        'primary-dim': '#9cc1a9',
        'primary': '#a9cfb7',
        'surface-container-high': '#1c211e',
        'outline': '#717773',
        'on-primary-container': '#b3d9c0',
        'surface-container-low': '#111413',
        'on-background': '#e1e7e2',
        'error-dim': '#bb5551',
        'tertiary': '#f3fbf6',
        'surface-variant': '#212724',
        'secondary': '#8ba1ac',
        'secondary-container': '#2a3e47',
        'on-secondary-container': '#adc3ce',
        'on-primary': '#254734',
        'surface-container-lowest': '#000000',
        'on-surface-variant': '#a6aca8',
        'on-error-container': '#ff9993',
        'background': '#0d0f0e',
        'on-surface': '#e1e7e2',
        'error': '#ee7d77',
        'error-container': '#7f2927',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
